Juvix to Isabelle/HOL translation
anoma/juvix pull request #2752
Opened 2024-04-22 17:13 UTC by lukaszcz

* Closes #2689 
* Adds the command `juvix isabelle program.juvix` which translates a given file to an Isabelle/HOL theory.
* Currently, only a single module is translated.
* By default translates types and function signatures. Translating function signatures can be disabled with the `--only-types` option.

Blocked by:
- https://github.com/anoma/juvix/issues/2763

2024-04-25 17:02 UTC, jonaprieto commented
> How do we test HTML and Markdown generation?

For Markdown, we have tests in `test/BackendMarkdown/` and smoke tests. For Html, as I as I remember, we only have smoke tests. 

> any ideas of how this could be tested?

Let's install Isabelle in the CI, and test with it that the generation produces valid theories.

2024-04-26 15:29 UTC, janmasrovira submitted a review, later dismissed

2024-04-26 17:42 UTC, jonaprieto requested changes
Wait for me, I need to test with some examples from the specs, before merging this.

2024-05-02 12:02 UTC, jonaprieto commented on src/Juvix/Compiler/Backend/Isabelle/Pretty/Base.hs
> +    n <- ppCode _theoryName
The theory's name must correspond to the file's name. Currently, it's printing the qualified name of the Juvix module.

2024-05-06 14:40 UTC, jonaprieto commented on src/Juvix/Compiler/Backend/Isabelle/Pretty/Base.hs
> +    n <- ppCode _theoryName
That won't work either. Use the unqualified name of the module as the name of the theory.

2024-05-06 14:51 UTC, jonaprieto commented on src/Juvix/Compiler/Backend/Isabelle/Pretty/Base.hs
> +    n <- ppCode _theoryName
Indeed. But we can generate the Isabelle theories following the module's folder structure of the Juvix modules. We do this for HTML output.

2024-06-05 10:23 UTC, jonaprieto approved these changes

2024-06-05 10:23 UTC, merged