Isabelle/HOL translation: recursive translation of the whole project
anoma/juvix pull request #2977
Opened 2024-08-28 16:58 UTC by lukaszcz

* Closes #2906 
* Isabelle/HOL does not support module name aliases (the `as` keyword of Juvix), which requires a workaround.

Checklist
---------
- [x] Pipeline infrastructure to process arbitrary Juvix pipelines recursively
- [x] CLI
- [x] Theory names
- [x] Qualified names
- [x] Qualified imports with alias

2024-09-13 16:32 UTC, janmasrovira commented on app/Commands/Isabelle.hs
> +              putStrLn ""
```suggestion
          | opts ^. isabelleStdout -> renderStdOutLn (ppOutDefault comments thy)
```

2024-09-13 16:32 UTC, janmasrovira commented on src/Juvix/Compiler/Backend/Isabelle/Translation/FromTyped.hs
> +          map (^. Internal.importModuleName) (_moduleBody ^. Internal.moduleImports),
merge two maps

2024-09-14 06:32 UTC, janmasrovira approved these changes

2024-09-14 07:26 UTC, paulcadman requested changes
We need to postpone merging this until I can resolve:

* https://github.com/anoma/juvix/issues/3037

as we may need to rollback the GHC 9.10.1 upgrade if I cannot resolve it.

2024-09-19 17:04 UTC, paulcadman commented
This PR is blocked until we can solve:

* https://github.com/anoma/juvix/issues/3037

Which probably means we need to wait for stackage nightly to update to GHC 9.10.1.

2025-06-03 16:24 UTC, janmasrovira approved these changes

2025-06-03 16:25 UTC, merged